apiVersion: v1

kind: Service

metadata:

  name: frontend

spec:

  selector:

    app: flatb

    tier: frontend

  ports:

  - protocol: TCP

    port: 80

    targetPort: 80

  type: LoadBalancer

---

apiVersion: apps/v1

kind: Deployment

metadata:

  name: frontend

spec:

  selector:

    matchLabels:

      app: flatb

      tier: frontend

  replicas: 1

  template:

    metadata:

      labels:

        app: flatb

        tier: frontend

    spec:

      containers:

        - name: flatb-nginx

          image: sksznddl1/flatb-front
